### ISSUE TITLE
Vote sur la proposition de réconciliation / fusion avec node.js

### ISSUE THREAD

**Issue by tdd** [nodejs/iojs-fr#32]
Hello les gars,

Vous avez sûrement vu https://github.com/iojs/io.js/issues/978, qui nous a été notifiée, comme à tous les groupes de trads et WG de io.js…

Il nous faut donc gérer ici un vote quant à l'opportunité de cette fusion. Je propose qu'on aie cette discussion dans cette *issue*, après quoi on signalera le résultat du vote dans la leur.

Personnellement, **je suis pour la fusion, dès lors que les modalités décrites par la proposition sont respectées**.

Côté i18n, node.js vient d'intégrer ECMA402 et le global `Intl`, ce qui est cool, même si je serais assez pour avoir deux distribs à terme (un des collaborateurs proposait "Bare" et "Extra"), vu que l'ICU rajoute près de 3Mo au binaire, qu'on ne peut pas facilement lier à une lib dynamique système de façon homogène, et que y'aura des tas de cas légers (microcontrôleurs, etc.) qui ne voudront pas avoir cette taille de binaire…

On est 14 sur ce groupe, essayons d'aboutir à un vote aussi vite que possible :smile:

**Comment by tdd** [comment]
Ah oui, et comme on n'est pas auto-notifiés par les issues, je pinge explicitement @iojs/iojs-fr

**Comment by Schmoopiie** [comment]
J'aime bien le modèle de gouvernance ouvert de io.js, si ce modèle peut rester après la fusion et que les updates qui ont été fait sur les streams restent, alors je suis pour :+1:

**Comment by Nicolab** [comment]
Perso ce fork ça fait des mois que je l'attendais, heureux qu'il soit fait par des gens déjà impliqués dans Node (contributeurs principaux, etc).

Un truc rédhibitoire pour moi concernant la fusion, est que Joyent détient la marque Node.js. A partir de là ils peuvent contrôler l'usage du nom "Node.js" et "Node", donc autoriser telle société à ouvrir un service nommé "NodeUnService" par exemple mais interdire une autre de le faire (déjà vue, il y a des articles sur ces pratiques de Joyent).

Ils ont autorisés certaines communautés locales au début (NodeBR.com, nodejs.ir, nodejs.org.au, nodejs.es, ...) et interdit d'autres par la suite.

Alors que io.js en moins d'une semaine, tout c'est mis en place au niveau des groupes locaux. Avec la prise en compte des remarques et suggestions, sans compter l'enthousiasme agréable qui gravite autour d'io.js.

Cette organisation est excellente et fait ses preuves en très peu de temps. Je suis curieux de voir ce que ça donne en continuant dans cette lancée, fusionner avec Joyent/Node je me doute déjà de la suite vue la mentalité.

En bref, pourquoi s'emmerder avec la politique :)

**Comment by Nicolab** [comment]
Il semble que si fusion il y a, la propriété de la marque sera transférée à la fondation.
Mais bon Joyent dans le TC, ça va être politique la cohabitation ....

**Comment by yrezgui** [comment]
Si on perd pas au change, je suis pour. L'idée d'avoir deux communautés je suis pas spécialement fan. Je vois plutôt io.js comme un Chrome Canary et NodeJS comme le stable.

**Comment by Nicolab** [comment]
Je vois plutôt comme MariaDB et MySQL.

**Comment by yrezgui** [comment]
Si on est sûr d'avoir une diversité des acteurs décisionnels, je vois pas où est le problème. Le fait qu'actuellement, Joyent a trop de pouvoir dans NodeJS est gênant. Mais si la fondation est open, je suis good.

**Comment by tdd** [comment]
@Nicolab la fusion passe par l'adoption de GOVERNANCE.md, qui notamment prévoit qu'aucun employeur ne peut avoir plus d'1/3 du TC, ce qui limitera le poids « politique » de toute société.  Et oui, les marques, toutes, passeraient sous contrôle de la fondation.

Du coup je pense qu'ils se sont bien bordés côté gouvernance, au niveau des postulats et prérequis *sine qua non* pour la fusion.

**Comment by cedced19** [comment]
Si on perd pas les avantage qu'on a reçu avec io.js __je suis pour__.

**Comment by tdd** [comment]
Je vous invite à suivre les inquiétudes et réponses à celles-ci sur l'issue d'origine.

**Comment by yoannmoinet** [comment]
Avec le respect des modalités énoncées, **je suis aussi pour la réconciliation**.

Il me semble que certains des objectifs du fork iojs étaient notamment de montrer la possibilité d'avoir une meilleure gouvernance, des mises à jour plus fréquentes, un meilleur support V8, ES6 etc... et ils ont été remplis avec brio.

**Comment by abenhamdine** [comment]
Personnellement, je trouve qu'il est trop tôt pour voter.
La réconciliation ne peut avoir lieu que si les principes de io.js (gouvernance ouverte, avancée technologique rapide, etc...) sont préservés, et pour l'instant, la fondation Node n'était pas constituée, il est difficile de savoir si ces principes seront en accord avec le mode de fonctionnement de cette fondation.

+1 sur le principe de la réconciliation néanmoins, dès lors qu'évidemment les conditions énoncées dans la proposition ne sont pas fondamentalement remises en cause (notamment sur la gouvernance).

Disons que la proposition est un bon point de départ par démarrer une discussion sur la réconciliation.

**Comment by podefr** [comment]
il semble qu'on n'ait plus besoin de ce ticket :)
