### ISSUE TITLE
Scope de notre groupe de l18n

### ISSUE THREAD

**Issue by thaume** [nodejs/iojs-fr#7]
D'après vous quel est le scope de ce groupe au delà du travail de traduction et d'évangélisation via twitter et autres ? Devrions nous organiser des meetups ? Votre opinion ?

**Comment by pierreinglebert** [comment]
Ne risque-t-on pas de rentrer en conflit avec les meetups nodejs ?
A moins que ceux-ci refusent de parler d'iojs (ce ne sont pas des employés de Joyent donc je pense pas), je ne vois pas pourquoi scinder une communauté encore jeune.

**Comment by thaume** [comment]
Il faudrait se rapprocher d'eux tu as raison ! Je parlais plus de lancer le
mouvement que de créer un nouveau meetup :)

Le dim. 8 févr. 2015 16:39, Pierre Inglebert <notifications@github.com> a
écrit :

**Comment by yrezgui** [comment]
Il n'y a jamais eu une officialisation de teams NodeJS basées sur des langues étrangères. Donc je pense qu'avoir un vrai statut pour le travail d'évangélisation et de traduction est déjà un gros travail.

**Comment by maxlath** [comment]
+1 pour associer les communautés déjà existantes : les meetups NodeJs mais aussi la nodeschool qui s'active depuis peu à Paris ([repo](http://www.meetup.com/nodeschool-Paris/), [meetup](http://www.meetup.com/nodeschool-Paris/))

**Comment by oncletom** [comment]
Yep, ça reste le même écosystème — c'est juste un runtime plus moderne.

**Comment by tdd** [comment]
Et puis étant l'organisateur de NodeSchool Paris, je sers de pont :wink:

**Comment by tdd** [comment]
Ah oui et par ailleurs : on a au moins le scope [défini dans la roadmap](http://roadmap.iojs.org/?full#10), donc la trad du site (docs API comprises), des installeurs, etc. Ça me semble super important.
