### ISSUE TITLE
Automatise la création d'issues à la publication

### ISSUE THREAD

**Issue by yoannmoinet** [nodejs/iojs-fr#78]
Je viens de créer une task IFTTT pour automatiser la création des issue lorsqu'une nouvelle news est publié sur le medium de iojs.

https://ifttt.com/recipes/313781-create-issue-when-a-new-blog-post-is-published

Pour l'instant elle est désactivée.
Qu'en pensez-vous?

EDIT : voici une capture de la task privée qui donne un peu plus de détails.

![image](https://cloud.githubusercontent.com/assets/597828/9090789/473173d2-3b6a-11e5-8c92-4e5e451589f5.png)

**Comment by cedced19** [comment]
Si c'est bien fait (comme actuellement) pourquoi pas?

**Comment by yoannmoinet** [comment]
Je peux l'activer pour quelques semaines, pour voir si ça inscrit bien les issues.
Puis on verra si on doit la garder ou la désactiver.

PS : actuellement, elle n'est pas activée.

**Comment by podefr** [comment]
C'est génial! Je vote pour!

**Comment by yoannmoinet** [comment]
Je l'ai activée.

Si ça fait trop n'importe quoi, on pourra soit peaufiner, soit désactiver.

**Comment by slester** [comment]
Excellent, merci de nous sauver un peu de temps (qui devient beaucoup de temps).

**Comment by yoannmoinet** [comment]
Ok, ça n'a pas marché cette semaine :sob: 
ils ont changé le titre de l'article et il n'y a plus de `Week of` dans le titre, ce dont je me servais pour filtrer le RSS.

J'ai créé une nouvelle task qui sera exécutée dès qu'il y a un nouveau post, sans filtre.

**Comment by yoannmoinet** [comment]
Comme vous pouvez le voir tout ça fonctionne #79 .
Je vais closer ça du coup.

**Comment by podefr** [comment]
Excellent!!
